"""empty message

Revision ID: 2d4ea805410b
Revises: 863122c7a1d7
Create Date: 2021-02-15 19:28:37.812849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4ea805410b'
down_revision = '863122c7a1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'show_end')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('show_end', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
